CREATE TABLE IF NOT EXISTS af_salesplan_branch_plan (
	ID INT NOT NULL AUTO_INCREMENT,
	BRANCH_ID VARCHAR(32) NOT NULL,
	PERIOD_YEAR INT NOT NULL,
	PERIOD_MONTH INT NOT NULL,
	AMOUNT DECIMAL(18,2) NOT NULL DEFAULT 0,
	CURRENCY CHAR(3) NOT NULL DEFAULT 'KZT',
	DATE_CREATE DATETIME NULL,
	DATE_MODIFY DATETIME NULL,
	CREATED_BY INT NULL,
	MODIFIED_BY INT NULL,
	PRIMARY KEY (ID),
	UNIQUE KEY UX_AF_SP_BRANCH_PERIOD (BRANCH_ID, PERIOD_YEAR, PERIOD_MONTH)
);

CREATE TABLE IF NOT EXISTS af_salesplan_user_plan (
	ID INT NOT NULL AUTO_INCREMENT,
	BRANCH_ID VARCHAR(32) NOT NULL,
	USER_ID INT NOT NULL,
	PERIOD_YEAR INT NOT NULL,
	PERIOD_MONTH INT NOT NULL,
	AMOUNT DECIMAL(18,2) NOT NULL DEFAULT 0,
	CURRENCY CHAR(3) NOT NULL DEFAULT 'KZT',
	DATE_CREATE DATETIME NULL,
	DATE_MODIFY DATETIME NULL,
	CREATED_BY INT NULL,
	MODIFIED_BY INT NULL,
	PRIMARY KEY (ID),
	UNIQUE KEY UX_AF_SP_USER_PERIOD (BRANCH_ID, USER_ID, PERIOD_YEAR, PERIOD_MONTH),
	KEY IX_AF_SP_USER (USER_ID)
);

CREATE TABLE IF NOT EXISTS af_salesplan_audit (
	ID INT NOT NULL AUTO_INCREMENT,
	ENTITY_TYPE VARCHAR(32) NOT NULL,
	ENTITY_ID INT NULL,
	BRANCH_ID VARCHAR(32) NOT NULL,
	USER_ID INT NULL,
	PERIOD_YEAR INT NOT NULL,
	PERIOD_MONTH INT NOT NULL,
	FIELD_NAME VARCHAR(64) NOT NULL,
	OLD_VALUE VARCHAR(255) NULL,
	NEW_VALUE VARCHAR(255) NULL,
	CHANGED_BY INT NOT NULL,
	CHANGED_AT DATETIME NOT NULL,
	PRIMARY KEY (ID),
	KEY IX_AF_SP_AUDIT_BRANCH (BRANCH_ID, PERIOD_YEAR, PERIOD_MONTH)
);
