services:
  asterisk:
    image: andrius/asterisk:20
    container_name: asterisk-beeline
    network_mode: host
    restart: unless-stopped
    environment:
      TZ: Asia/Almaty
    volumes:
      - ./config:/etc/asterisk:ro
      - ./logs:/var/log/asterisk
    cap_add:
      - SYS_NICE
      - NET_ADMIN
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
