[modules]
autoload=yes
noload => chan_sip.so
noload => chan_skinny.so
noload => chan_mgcp.so
noload => chan_unistim.so
noload => chan_alsa.so
noload => chan_oss.so
noload => chan_console.so
noload => cdr_sqlite3_custom.so
noload => cdr_pgsql.so
noload => cdr_odbc.so
noload => cel_odbc.so
noload => cel_pgsql.so
noload => cel_sqlite3_custom.so
noload => res_hep.so
noload => res_hep_pjsip.so
noload => res_hep_rtcp.so
noload => res_pjsip_phoneprov_provider.so
noload => res_phoneprov.so
noload => res_stun_monitor.so
load => res_pjsip.so
load => res_pjsip_session.so
load => res_pjsip_registrar.so
load => res_pjsip_outbound_registration.so
load => res_pjsip_outbound_authenticator_digest.so
load => res_pjsip_authenticator_digest.so
load => res_pjsip_endpoint_identifier_ip.so
load => res_pjsip_endpoint_identifier_user.so
load => chan_pjsip.so
load => res_rtp_asterisk.so
